#!/bin/bash

echo "🦦 Капибара начинает деплой на Render.com!"
echo ""
echo "Следуй инструкциям:"
echo ""
echo "1. Зайди на https://render.com и залогинься"
echo ""
echo "2. Создай WEB SERVICE для API:"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "   - Environment Variables:"
echo "     TELEGRAM_BOT_TOKEN = твой токен"
echo "     MINI_APP_URL = (заполнишь после деплоя frontend)"
echo ""
echo "3. Создай BACKGROUND WORKER для бота:"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: cd backend && python bot.py"
echo "   - Environment Variables: те же что и выше"
echo ""
echo "4. Задеплой Frontend на Vercel:"
echo "   npm run build"
echo "   npx vercel --prod"
echo ""
echo "5. После деплоя frontend обнови MINI_APP_URL в Render"
echo ""
echo "6. Настрой Mini App в @BotFather:"
echo "   /mybots -> выбери бота -> Bot Settings -> Menu Button"
echo "   Укажи URL твоего frontend"
echo ""
echo "Готово! 🦦"
